name: Terraform - prod (plan)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - "accounts/prod/**"
      - "modules/**"
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to (re-)plan against"
        required: true
        
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    uses: ./.github/workflows/_terraform-plan-reusable.yml
    with:
      environment: prod
      pr_number: ${{ github.event.pull_request.number || inputs.pr_number }}
    secrets: inherit
